### ISSUE TITLE
Creating a server with this.

### ISSUE THREAD

**Issue by M2HF** [ModificationStation/AetherMP#2]
Hey, I just came across this, looking to create a beta 1.7.3 Aether server.
Now I'm wondering how I'd set up a server with this.
Is this a plugin? Do people have to install special versions of the mod on their clients? Which files go where?

I'd would be great if you could help me.
Maybe this belongs in the readme.md as well.

Thanks in advance!

**Comment by Meefy777** [comment]
Hey there!

The version of AetherMP on this github has been abandoned by the developer. It is usable but there is a lot of missing content and quite a few bugs. Luckily for you I forked it and basically completed it. 

Join this discord server: https://discord.gg/vUuKQPM

To answers your questions
1.There is a tutorial in the discord server
2.It is a mod, there is a plugin side to it for certain features but it is mainly a mod since a plugin can't add in custom items/blocks etc.
3.You don't need a special version of Aether, but you will need to install the Client AetherMP addon which patches Aether to work with multiplayer.
